#!/usr/bin/env python3

import sys
import re

def main():
    query_id = None
    for line in sys.stdin:
        match = re.search(r'\{(.*?)\}', line)
        if match and match.group(1):
            new_query_id = match.group(1)
            if query_id != new_query_id:
                query_id = new_query_id
                sys.stdout.write('-' * 100 + '\n')
        sys.stdout.write(line)
        sys.stdout.flush()




if __name__ == '__main__':
    main()
